export default {
  1: [
    {
      icon: 'mdi-briefcase-account-outline',
      title: 'Daftar Riwayat Hidup (CV)',
      subtitle: '(Langkah 1)',
      desc: 'Pada langkah ini Anda diharuskan melengkapi semua informasi Biodata Diri Anda',
      color: 'green',
      deepColor: '',
      akses: true,
      // disable: true,
      key: 'cv',
      action: 'cv',
    },
    {
      icon: 'mdi-square-edit-outline',
      title: 'Esai',
      subtitle: '(Langkah 2)',
      desc: 'Pada langkah ini Anda diharuskan menyelesaikan semua pertanyaan Esai yang telah disediakan',
      color: 'orange',
      deepColor: '',
      akses: true,
      // disable: true,
      key: 'esai',
      action: 'esai',
    },
    {
      icon: 'mdi-brain',
      title: 'Tes Bakat Skolastik <br>Susulan/Ulang',
      subtitle: '(Langkah 3)',
      desc: `Pada langkah ini Anda diharuskan untuk menjawab tes yang telah disediakan - 
            <b>menunggu jadwal dari Pusat</b>`,
      color: 'blue',
      deepColor: '',
      akses: true,
      disable: true,
      key: 'tbs',
      action: 'tbs',
    },
    {
      icon: 'mdi-brain',
      title: '<b><u>Uji Coba</u></b> Tes Bakat Skolastik',
      subtitle: '(8 Maret 2020)',
      desc:
        'Pelaksanaan <strong>uji coba</strong> Tes Bakat Skolastik ini ' +
        'akan tersedia pada tanggal <strong>8 Maret November 2020 (Jam 08.00 - 16.00 WIB)</strong>',
      color: 'purple',
      deepColor: '',
      akses: false,
      disable: true,
      key: 'tbs-demo',
      action: 'tbs-demo',
    },
    {
      icon: 'mdi-web',
      title: 'Portal Sekolah Penggerak',
      desc: '',
      color: 'secondary',
      deepColor: 'darken-2',
      dividerTop: true,
      sidebar: true,
      akses: true,
      newtab: true,
      href: '#PORTAL_URL#',
    },
    {
      icon: 'mdi-webhook',
      title: 'ke Aplikasi SIMPKB',
      desc: '',
      color: 'secondary',
      deepColor: 'darken-2',
      sidebar: true,
      akses: true,
      link: 'app-sim-pkb',
      href: '#SIM_PKB_URL#',
    },
  ],
  2: [
    {
      icon: 'mdi-teach',
      title: 'Simulasi & Wawancara',
      subtitle: '',
      desc: '',
      color: 'pink',
      deepColor: 'darken-1',
      akses: true,
      key: 'microteaching',
      disable: false,
      action: 'microteaching',
    },
    {
      icon: 'mdi-web',
      title: 'Portal Sekolah Penggerak',
      desc: '',
      color: 'secondary',
      deepColor: 'darken-2',
      dividerTop: true,
      sidebar: true,
      akses: true,
      newtab: true,
      href: '#PORTAL_URL#',
    },
    {
      icon: 'mdi-webhook',
      title: 'ke Aplikasi SIMPKB',
      desc: '',
      color: 'secondary',
      deepColor: 'darken-2',
      sidebar: true,
      akses: true,
      link: 'app-sim-pkb',
      href: '#SIM_PKB_URL#',
    },
  ],
};
